using DeviceManager.Api.Data.DataSeed;
using DeviceManager.Api.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace DeviceManager.Api.Data
{
    /// <summary>
    /// The device DB (entity framework's) context
    /// </summary>
    public class DeviceContext : DbContext, IDbContext
    {
        private readonly IDataSeeder dataSeeder;
        private readonly ILoggerFactory loggerFactory;

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceContext"/> class.
        /// </summary>
        /// <param name="options">The options.</param>
        /// <param name="dataSeeder">Initial data seeder</param>
        /// <param name="loggerFactory">Configured logger factory</param>
        public DeviceContext(DbContextOptions<DeviceContext> options, IDataSeeder dataSeeder, ILoggerFactory loggerFactory)
            : base(options)
        {
            this.dataSeeder = dataSeeder;
            this.loggerFactory = loggerFactory;
            // TODO: Comment below this if you are running migrations commands
            // TODO: uncomment below line of you are running the application for the first time
            //this.Database.EnsureCreated();
        }

        /// <summary>
        /// Get or sets the devices data model
        /// </summary>
        public DbSet<Device> Devices { get; set; }

        /// <summary>
        /// Get or sets the device groups data model
        /// </summary>
        public DbSet<DeviceGroup> DeviceGroups { get; set; }

        /// <inheritdoc/>
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            // Logs queries generated by entity framework into the configured logger.
            // Logs queries with data in debug mode but not in release mode.
            optionsBuilder
                .UseLoggerFactory(this.loggerFactory)
#if DEBUG
                .EnableSensitiveDataLogging()
#endif
                ;
        }

        /// <summary>
        /// Relation between tables.
        /// </summary>
        /// <param name="modelBuilder">Entity framework model builder before creating database</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Device>()
                .HasKey(device => new { device.DeviceId });

            // No need to define the relation explicitly as long as conventions are followed.

            modelBuilder.Entity<Device>()
                .HasOne(device => device.DeviceGroup)
                .WithMany(group => group.Devices)
                .HasForeignKey(device => device.DeviceGroupId);

            // Call Data seeder
            this.dataSeeder.SeedData(modelBuilder);
        }
    }
}
