// <auto-generated />
using System;
using DeviceManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DeviceManager.Api.Migrations
{
    [DbContext(typeof(DeviceContext))]
    [Migration("20181005141301_DeviceGroup")]
    partial class DeviceGroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DeviceManager.Api.Data.Model.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DeviceGroupId");

                    b.Property<string>("DeviceTitle");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceGroupId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceManager.Api.Data.Model.DeviceGroup", b =>
                {
                    b.Property<Guid>("DeviceGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<string>("OperatingSystem");

                    b.HasKey("DeviceGroupId");

                    b.ToTable("DeviceGroup");
                });

            modelBuilder.Entity("DeviceManager.Api.Data.Model.Device", b =>
                {
                    b.HasOne("DeviceManager.Api.Data.Model.DeviceGroup", "DeviceGroup")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
